# github actions workflow that has two jobs just printing out some text
# and then a third job that depends on the first two jobs
# and prints out some more text
name: workflow1
on:
  pull_request:
    branches: [main]
jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - name: step1
        run: echo "step1"
      - name: step2
        run: echo "step2"
  job2:
    runs-on: ubuntu-latest
    steps:
      - name: step3
        run: echo "step3"
      - name: step4
        run: echo "step4"
  job3:
    runs-on: ubuntu-latest
    needs: [job1, job2]
    steps:
      - name: step5
        run: echo "step5"
      - name: step6
        run: echo "step6"
