# github actions workflow that has two jobs just printing out some text
# and then a third job that depends on the first two jobs
# and prints out some more text
name: workflow1
on:
  push:
    branches: [main]
  pull_request:
    types:
      - "labeled"
  workflow_dispatch:
jobs:
  # this job creates output envs for other jobs
  creates-envs:
    if: github.event.label.name == 'trigerci'
    runs-on: ubuntu-latest
    outputs:
      env1: ${{ steps.step1.outputs.name }}
      env2: ${{ steps.step2.outputs.name }}
    steps:
      - name: step1
        id: step1
        run: |
          echo "name=env1" >> $GITHUB_OUTPUT
      - name: step2
        id: step2
        run: |
          echo "name=env2" >> $GITHUB_OUTPUT
  print-step-1:
    if: github.event.label.name == 'trigerci'
    runs-on: ubuntu-latest
    needs: creates-envs
    steps:
      - name: print-envs
        run: echo ${{ needs.creates-envs.outputs.env1 }} ${{ needs.creates-envs.outputs.env2 }}
  job2:
    if: github.event.label.name == 'trigerci'
    runs-on: ubuntu-latest
    steps:
      - name: step3
        run: echo "step3"
      - name: step4
        run: echo "step4"

